---
blank_issues_enabled: false

contact_links:
  - name: ğŸ’¡ Discuss an idea
    url: https://github.com/library_owner/library_name@latest/discussions/new?category=ideas
    about: Suggest a feature or an improvement.

  - name: â” Ask a question
    url: https://github.com/library_owner/library_name@latest/discussions/new
    about: Ask questions and discuss with other `library_name` users or maintainers.

  - name: ğŸ™ Request help
    url: https://github.com/library_owner/library_name@latest/discussions/new
    about: Ask the `library_name` community for help.
